server:
  port: 8081

spring:
  application:
    name: account
  kafka:
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092
      group-id: transaction-group
      properties:
        security.protocol: PLAINTEXT

    #specific.avro.reader: true
#        deserializer.trusted.packages: java.util,java.lang,com.micro.account.entity.*
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb?serverTimezone=UTC
    username: user
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER




##http://localhost:8088/swagger-ui/index.html
