server:
  port: 8081

spring:
  profiles:
    default: default
  application:
    name: account
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        prefer-ip-address: true
  datasource:
    url: jdbc:postgresql://consul:5432/accountdb?serverTimezone=UTC
    username: user
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER




#http://localhost:8088/swagger-ui/index.html
