spring:
  application:
    name: account
  cloud:
    consul:
      host: consul
      port: 8500
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8080

---

spring:
  profiles: dev
  application:
    name: account
  cloud:
    consul:
      host: localhost
      port: 8500
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 0