api:
  base-uri: "https://stsapiuat.walletgate.io/v1/Account/"
#--------------------------------------------------------------
server:
  port: 8080
spring:
  application:
    name: account
  cloud:
    consul:
      host: consul
      port: 8500
  datasource:
    password: passwordHEPCARDapp
    url: jdbc:postgresql://postgres:5432/account
    username: hepcardApp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  profiles:
    active: dev
#    cloud:
#      consul:
#        host: localhost
#        port: 8500
#      loadbalancer:
#        ribbon:
#          enabled: false
#
#  server:
#    port: 0
#spring:
#  application:
#    name: account
#  cloud:
#    consul:
#      host: consul
#      port: 8500
#    loadbalancer:
#      ribbon:
#        enabled: false
#
#server:
#  port: 8080
#
#---
#
#spring:
#  profiles:
#    active: dev
#    datasource:
#      password: passwordHEPCARDapp
#      url: jdbc:postgresql://postgres:5432/account
#      username: hepcardApp
#      driver-class-name: org.postgresql.Driver
#      jpa:
#        hibernate:
##          ddl-auto: update
#          ddl-auto: create
#        properties:
#          hibernate:
#            dialect: org.hibernate.dialect.PostgreSQLDialect
#            format_sql: true
#        show-sql: true
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#    loadbalancer:
#      ribbon:
#        enabled: false
#
#server:
#  port: 0
