server:
  port: 8088

spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://localhost:5432/hepcarddb
    username: hepcarduser
    password: hepcardpass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true
        format_sql: true
        jdbc:
          time_zone: UTC
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#http://localhost:8088/swagger-ui/index.html
