spring:
  profiles:
    default: docker
  application:
    name: account
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      properties:
        security.protocol: PLAINTEXT
        #specific.avro.reader: true
        deserializer.trusted.packages: java.util,java.lang,com.micro.account.entity.*,com.micro.transaction.entity.*
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        prefer-ip-address: true
  datasource:
    url: jdbc:postgresql://postgres:5432/accountdb?serverTimezone=UTC
    username: user
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER




##http://localhost:8088/swagger-ui/index.html
