version: "3.8"
services:
    consul:
        image: consul 
        ports:
            - "8500:8500"
            - "8600:8600/udp"
        container_name: consul
        command: ["agent", "-server", "-ui", "-node=server-1", "-bootstrap-expect=1", "-client=0.0.0.0"]

    config:
        build: ./config
        ports:
            - "8080"
        container_name: config-service
        restart: on-failure
        depends_on:
            - consul

    gateway:
        build: ./gateway
        ports:
            - "8080"
        container_name: gateway-service
        restart: on-failure
        depends_on:
            - consul

    order:
        build: ./order
        ports:
            - "8080"
        container_name: order-service
        restart: on-failure
        depends_on:
            - consul

    trader:
        build: ./trader
        ports:
            - "8080"
        container_name: trader-service
        restart: on-failure
        depends_on:
            - consul

    account:
        build: ./account
        ports:
            - "8080"
        container_name: account-service
        restart: on-failure
        depends_on:
            - consul
    
networks:
    default:
        name: spring-cloud-microservices