version: "3.8"
services:
  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    container_name: consul
    command: ["agent", "-server", "-ui", "-node=server-1", "-bootstrap-expect=1", "-client=0.0.0.0"]

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=raj@nola.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

#  account:
#    build: ./account
#    ports:
#      - "8081:8081"
#    container_name: account
#    restart: on-failure
#    networks:
#      - consul-net
#      - postgres-net
#    depends_on:
#      - consul
#      - postgres
#      - kafka
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/accountdb?serverTimezone=UTC
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=admin
#      - spring.cloud.consul.host=consul
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS=192.168.16.4:9092
#
#  transaction:
#    build: ./transaction
#    ports:
#      - "8083:8083"
#    container_name: transaction
#    restart: on-failure
#    networks:
#      - consul-net
#      - postgres-net
#    depends_on:
#      - consul
#      - kafka
#    environment:
#      - spring.cloud.consul.host=consul
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS=192.168.16.4:9092

volumes:
  local_pgdata:
  pgadmin-data: