server:
  port: 8085

spring:
  application:
    name: auth
  security:
    jwt:
      secret: "hepCardSecret"
  kafka:
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092
      group-id: authentication-group
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
