server:
  port: 8080

spring:
  profiles:
    default: default
  application:
    name: transaction
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        prefer-ip-address: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER




#http://localhost:8088/swagger-ui/index.html

