server:
  port: 8083

spring:
  application:
    name: transaction
  kafka:
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092
      group-id: transaction-group
      properties:
        security.protocol: PLAINTEXT
        #specific.avro.reader: true
#        deserializer.trusted.packages: java.util,java.lang,com.micro.transaction.entity.*
#    consumer:
#      group-id: my-consumer-group
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


#http://localhost:8082/swagger-ui/index.html

